name: CI

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Create Docker tag for web
        id: create_tag
        uses: InfraWay/gh-create-docker-tag@v3.2
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: '${{ steps.create_tag.outputs.name }}'
          cache-from: type=gha,scope=build
          cache-to: type=gha,mode=max,scope=build
      - run: |
          echo "### Docker image ${{ steps.create_tag_web.outputs.name }} pushed to registry :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "### Docker image ${{ steps.create_tag_static.outputs.name }} pushed to registry :rocket:" >> $GITHUB_STEP_SUMMARY
        name: Print workflow summary
